### ISSUE TITLE
尝试获取二维码扫描图片时报错

### ISSUE THREAD

**Issue by cyxnzb** [thuhollow2/Hetangyuketang#3]
出现异常，尝试重试 (4/1000)
登录二维码已保存为qrcode.jpg
Traceback (most recent call last):
  File "隐去/yuketang.py", line 299, in ws_controller
    await func(*args)
  File "隐去/yuketang.py", line 323, in ws_login
    self.msgmgr.sendImage("qrcode.jpg")
  File "隐去/send.py", line 116, in sendImage
    send_wx_image(upload_wx_file(path))
  File "隐去/send.py", line 226, in upload_wx_file
    media_ids.append(r.json()['media_ids'])
KeyError: 'media_ids'

**Comment by thuhollow2** [comment]
> 出现异常，尝试重试 (4/1000) 登录二维码已保存为qrcode.jpg Traceback (most recent call last): File "隐去/yuketang.py", line 299, in ws_controller await func(*args) File "隐去/yuketang.py", line 323, in ws_login self.msgmgr.sendImage("qrcode.jpg") File "隐去/send.py", line 116, in sendImage send_wx_image(upload_wx_file(path)) File "隐去/send.py", line 226, in upload_wx_file media_ids.append(r.json()['media_ids']) KeyError: 'media_ids'

改过还有吗？

**Comment by cyxnzb** [comment]
> > 出现异常，尝试重试 (4/1000) 登录二维码已保存为qrcode.jpg Traceback (most recent call last): File "隐去/yuketang.py", line 299, in ws_controller await func(*args) File "隐去/yuketang.py", line 323, in ws_login self.msgmgr.sendImage("qrcode.jpg") File "隐去/send.py", line 116, in sendImage send_wx_image(upload_wx_file(path)) File "隐去/send.py", line 226, in upload_wx_file media_ids.append(r.json()['media_ids']) KeyError: 'media_ids'
> 
> 改过还有吗？

没改，好像跟企业微信有关，我把发送通知关了后就正常了。。不知道是我的企业微信配置没配置好还是代码bug

**Comment by thuhollow2** [comment]
> > > 出现异常，尝试重试 (4/1000) 登录二维码已保存为qrcode.jpg Traceback (most recent call last): File "隐去/yuketang.py", line 299, in ws_controller await func(*args) File "隐去/yuketang.py", line 323, in ws_login self.msgmgr.sendImage("qrcode.jpg") File "隐去/send.py", line 116, in sendImage send_wx_image(upload_wx_file(path)) File "隐去/send.py", line 226, in upload_wx_file media_ids.append(r.json()['media_ids']) KeyError: 'media_ids'
> > 
> > 
> > 改过还有吗？
> 
> 没改，好像跟企业微信有关，我把发送通知关了后就正常了。。不知道是我的企业微信配置没配置好还是代码bug

应该是企业微信没配置可信ip，你需要将运行环境的ip填到白名单里

**Comment by cyxnzb** [comment]
> > > > 出现异常，尝试重试 (4/1000) 登录二维码已保存为qrcode.jpg Traceback (most recent call last): File "隐去/yuketang.py", line 299, in ws_controller await func(*args) File "隐去/yuketang.py", line 323, in ws_login self.msgmgr.sendImage("qrcode.jpg") File "隐去/send.py", line 116, in sendImage send_wx_image(upload_wx_file(path)) File "隐去/send.py", line 226, in upload_wx_file media_ids.append(r.json()['media_ids']) KeyError: 'media_ids'
> > > 
> > > 
> > > 改过还有吗？
> > 
> > 
> > 没改，好像跟企业微信有关，我把发送通知关了后就正常了。。不知道是我的企业微信配置没配置好还是代码bug
> 
> 应该是企业微信没配置可信ip，你需要将运行环境的ip填到白名单里

ok了
