### ISSUE TITLE
提一些小小的建议

### ISSUE THREAD

**Issue by cyxnzb** [thuhollow2/Hetangyuketang#5]
1.可否实现直接输出二维码在bash，这个我看如果配置了机器人推送的话会发送二维码给用户，但是如果没配置的话，就得自行在程序目录下寻找二维码图片扫码登录

2.登录成功感知不强，扫码后仅在配置机器人后会有成功提示，在bash没有任何反应，只能ctrl+c强制结束

3.教师翻阅课件时会保存课件内容，这个功能好像是强制的？有地方修改吗

**Comment by thuhollow2** [comment]
1.已实现终端显示二维码
2.修改了，以显示cookie有效性方式提示
3.增加self.ppt控制是否下载ppt

**Comment by cyxnzb** [comment]
> 1.已实现终端显示二维码 2.修改了，以显示cookie有效性方式提示 3.增加self.ppt控制是否下载ppt

好，辛苦啦
